### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by finzaiko** [ikandars/gia#1]
Mas Kandar,

Saya suka banget app blog ini simple tanpa database, saya sudah clone projectnya kemudian saya rename foldernya menjadi giablog ketika saya akses :
http://localhost/giablog/public/ page not found kira kenapa ya mas ? (saya menggunakan xampp)

**Comment by ikandars** [comment]
Oke nanti coba saya reproduce errornya 
On May 16, 2016 8:16 AM, Arifin notifications@github.com wrote:Mas Kandar,

Saya suka banget app blog ini simple tanpa database, saya sudah clone projectnya kemudian saya rename foldernya menjadi giablog ketika saya akses :
http://localhost/giablog/public/ page not found kira kenapa ya mas ? (saya menggunakan xampp)

**Comment by ikandars** [comment]
Hallo mas, bisa coba dengan cara ini https://github.com/ikandars/gia/issues/3#issuecomment-247823407

Saya test dengan apache sudah jalan.

thx
