### ISSUE TITLE
Blog post links from main page are not correct

### ISSUE THREAD

**Issue by tyeeman** [ikandars/gia#3]
My link to Hello World post is 

```
/1-hello-world
```

I get "The requested URL /1-hello-world was not found on this server" from Apache. The path is incorrect. Where do I fix this?

**Comment by ikandars** [comment]
Let me test on my environment first.

**Comment by ikandars** [comment]
Hi,

First, ensure you have enable all required option in you Apache config for htaccess and mode rewrite. You can read more about this in this article https://www.digitalocean.com/community/tutorials/how-to-use-the-htaccess-file Then, set your Directory section and add `AllowOverride All`, The section should now look like this:

```
<Directory /var/www/gia/public>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
 </Directory>
```

Next, add an `.htaccess` file in public dir

```
RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
```

After you save and exit that file, restart apache.

```
sudo service apache2 restart
```

**Comment by tyeeman** [comment]
Thanks, works good. I just needed the htaccess file to make it work. Categories would be nice though. There is no way to search the blog.
